### ISSUE TITLE
error posting stat to stathat

### ISSUE THREAD

**Issue by dstroot** [stathat/stathat-issues#10]
Using Go - thingy no worky...

I initially cut and pasted the suggested code.  Obviously my real account info is redacted.  

code:

```
stathat.PostEZCount("Email Sent", "xxxxxxxxxx", 1)
stathat.PostEZValue("Email Template", "xxxxxxxxxxxx", float64(template))
```

errors:

```
2016/04/09 07:53:05 error posting stat to stathat: Post https://api.stathat.com/ez: x509: certificate is valid for Common Name (eg, YOUR name), not api.stathat.com
2016/04/09 07:53:05 error posting stat to stathat: Post https://api.stathat.com/ez: x509: certificate is valid for Common Name (eg, YOUR name), not api.stathat.com
```

**Comment by sleepyfox** [comment]
I have a similar symptoms using the EZ API or cURL, but no errors - instead I get a response like:
`{"status":200,"msg":"ok","multiple":1}`
But the stat never appears in either the web view or via the JSON API...

**Comment by stathat** [comment]
@dstroot Can't reproduce.  Feel free to reopen if you still have issue.
