### ISSUE TITLE
Unable to add any new stats

### ISSUE THREAD

**Issue by Overv** [stathat/stathat-issues#13]
When I use the `New stat` form I get a system error. When I try to submit data for a new statistic using the cURL example I get a successful response, but no graph appears even after a couple of hours of submitting one request per minute.

Existing statistics appear to be unaffected.

**Comment by patrickxb** [comment]
This should be fixed.  Sorry for the issue and thanks for the report.

**Comment by sleepyfox** [comment]
I have the same issue: when I use cURL or the EZ API to send counts to new stats, they never appear. I have emailed support@ with details.

**Comment by patrickxb** [comment]
Just fixed.
