### ISSUE TITLE
Graphs occasionally show intervals of missing data that reappears later on the same day

### ISSUE THREAD

**Issue by Overv** [stathat/stathat-issues#6]
On some days the graphs for my statistics show data missing for an interval of a few hours. I checked my application and it reported no problems sending stats to StatHat during that time. Later that day (near midnight @ CES) the missing data magically appears.

This has already happened to me for a couple days in the past week.

**Comment by patrickxb** [comment]
Yes, we're working on this.  There's no data loss, but there's a cache server issue.  Sorry for the inconvenience.

**Comment by lioniren** [comment]
![image](https://cloud.githubusercontent.com/assets/17242845/13691582/d4f9abd8-e742-11e5-92a9-c1c576699006.png)
