### ISSUE TITLE
Stats page shows two time interval indications at the top without a graph

### ISSUE THREAD

**Issue by Overv** [stathat/stathat-issues#7]
My stats page is showing two time interval texts like "1d @ 15m" at the top without any associated graph. Clicking them leads to a "Page not found" message:

![image](https://cloud.githubusercontent.com/assets/285063/13184377/c07f5f98-d73b-11e5-8ba4-63238a3ad1e1.png)

It seems like they are statistics that I deleted at some point, but something went wrong.

**Comment by stathat** [comment]
Fixed.
